changelog:
  exclude:
    labels:
      - "ignore-for-release"
      - "internal"
      - "chore"
  categories:
    - title: "🚀 New Features"
      labels:
        - "enhancement"
        - "feature"
    - title: "🐛 Bug Fixes"
      labels:
        - "bug"
        - "fix"
    - title: "📖 Documentation"
      labels:
        - "documentation"
    - title: "🛠️ Maintenance & Refactoring"
      labels:
        - "refactor"
        - "maintenance"
