= Esquemas UML

== Vehicles

[plantuml, linkers, png]
....
interface Linkable
interface Rotable
interface Selectable
interface Mapeable
interface Transportable
interface Trackeable
interface Renderable
interface Reversible
interface Tractor
abstract class Vehicle
abstract class Tracker
abstract class Linker

class Locomotive
class Trailer
class Wagon
class Train

Selectable <|.. Vehicle
Mapeable <|.. Vehicle
Rotable <|.. Vehicle
Renderable <|.. Vehicle
Reversible <|.. Vehicle
Renderable <|.. Trailer
Reversible <|.. Trailer
Transportable <|.. Vehicle
Trackeable <|.. Tracker
Tractor <|.. Locomotive
Vehicle <|-- Tracker
Linkable <|.. Linker
Tracker <|-- Linker
Linker <|-- Locomotive
Linker <|-- Wagon
Trailer o-- Linker :linkers
Trailer <|-- Train
....


== Rendering

[plantuml, renderers, png]
....
interface Renderer{
    {method} renderSim(GameModel model);
    {method} renderTrain(Train train);
    {method} renderMap(RailMap map);
    {method} renderRailTrack(RailTrack track);
    {method} renderStopRailTrack(StopRailTrack track);
    {method} renderTrainFactoryRailTrack(TrainFactoryRailTrack track);
    {method} renderTunnelRailTrack(TunnelRailTrack track);
    {method} renderLinker(Linker linker);
    {method} renderLocomotive(Locomotive locomotive);
    {method} renderWagon(Wagon wagon);
    {method} renderRailTrackMaker(RailTrackMaker railTrackMaker);
}

class UnicodeRenderer

interface Renderable{
    {method} accept(Renderer)
}

class Train
class Track
class Vehicle
class RailMap
class RailTrackMaker

Renderer <|.. UnicodeRenderer
Renderable <|.. Train
Renderable <|.. Track
Renderable <|.. Vehicle
Renderable <|.. RailMap
Renderable <|.. RailTrackMaker
....

== Tracks

[plantuml, tracks, png]
....
interface Router
interface Connectable
interface LinkerCompartment
interface Mapeable
interface LinkerCompartmentListener
interface Renderable

class Track
class RailTrack
class StopRailTrack
class TrainFactoryRailTrack
class TunnelRailTrack

Track <|-- RailTrack
RailTrack <|-- StopRailTrack
RailTrack <|-- TrainFactoryRailTrack
RailTrack <|-- TunnelRailTrack

Router <|.. Track
Connectable <|.. Track
LinkerCompartment <|.. Track
Mapeable <|.. Track
LinkerCompartmentListener <|.. Track
Renderable <|.. Track
....

== Model View Presenter

[plantuml, mvp, png]
....
interface GamePresenter
interface GameModel
interface GameView

class LeTrainView
class LeTrainPresenter
class LeTrainViewGrid
class LeTrainModel

GameModel <|.. LeTrainModel
GamePresenter <|.. LeTrainPresenter
GameView <|.. LeTrainView

LeTrainView *-- LeTrainViewGrid
GameView o-- GamePresenter
GamePresenter o-- LeTrainView
GamePresenter o-- GameModel

....