name: Build Snap Package

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install Snapcraft
        run: sudo snap install snapcraft --classic
        
      - name: Build Snap
        run: sudo snapcraft pack --destructive-mode
        
      - name: Upload Snap artifact
        uses: actions/upload-artifact@v4
        with:
          name: letrain-snap
          path: "*.snap"
